name: Deploy Backend to Railway

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Trigger Railway Deploy
        uses: railwayapp/railway-up@v1.2.0
        with:
          railwayToken: ${{ secrets.RAILWAY_API_TOKEN }}
          projectId: ${{ secrets.RAILWAY_PROJECT_ID }}
